//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTManagementPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Watches = new HashSet<Watch>();
        }
    
        public string Status { get; set; }
        public string Agent_ID { get; set; }
        public string Agent_Name { get; set; }
    
        public virtual ICollection<Watch> Watches { get; set; }
    }
}
