//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTManagementPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllAgent
    {
        public AllAgent()
        {
            this.AllWatchPoints = new HashSet<AllWatchPoint>();
        }
    
        public string TenantID { get; set; }
        public string AgentID { get; set; }
        public string AgentName { get; set; }
        public string AgentAlive { get; set; }
        public string LastAgentHeartBeat { get; set; }
    
        public virtual AllTenant AllTenant { get; set; }
        public virtual ICollection<AllWatchPoint> AllWatchPoints { get; set; }
    }
}
