//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTManagementPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllTenant
    {
        public AllTenant()
        {
            this.AllAgents = new HashSet<AllAgent>();
        }
    
        public string TenantID { get; set; }
        public string TenantName { get; set; }
        public string TenantDescription { get; set; }
        public string AgentsCount { get; set; }
        public string AgentsResponding { get; set; }
    
        public virtual ICollection<AllAgent> AllAgents { get; set; }
    }
}
