//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTManagementPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllWatchPoint
    {
        public string AgentID { get; set; }
        public string WatchPointID { get; set; }
        public string WatchPointName { get; set; }
        public string RootPath { get; set; }
    
        public virtual AllAgent AllAgent { get; set; }
    }
}
