//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTManagementPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watch
    {
        public string Watch_Point_ID { get; set; }
        public string Watch_Point_Name { get; set; }
        public string Agent_ID { get; set; }
        public string Watch_Point_Path { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
