//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTManagementPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WTPortalEntities : DbContext
    {
        public WTPortalEntities()
            : base("name=WTPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AllAgent> AllAgents { get; set; }
        public DbSet<AllTenant> AllTenants { get; set; }
        public DbSet<AllWatchPoint> AllWatchPoints { get; set; }
    }
}
